# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

platform :android do
  desc "Build AAB and upload to Google Play"
  lane :release do
    # Build app bundle (AAB)
    sh("flutter build appbundle --release")

    # Upload to Google Play
    upload_to_play_store(
      json_key: "google_play_key.json", # Created from GitHub Secret
      package_name: "com.example.rooster",
      aab: "build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
